### ISSUE TITLE
Query regarding Eth -> Substrate asset transfer 

### ISSUE THREAD

**Issue by jaxter03** [ChainSafe/chainbridge-substrate#87]
![Screenshot from 2021-03-07 22-14-13](https://user-images.githubusercontent.com/40355376/110247592-fce8cc80-7f92-11eb-9c55-be8b7acada6e.png)

Hey,
I need help regarding asset transfer. I want to transfer some other asset from Eth -> Substrate and also want to associate some other method with it. Could you help me what all I have to do for that?

**Comment by ansermino** [comment]
Hey @ksr30,

1. You'll need to implement another pallet with a method like [this](https://github.com/ChainSafe/chainbridge-substrate/blob/8f654c2b04c27409974b70a52a9a76b164f53d4d/example-pallet/src/lib.rs#L106-L110). It will be called as a result of successful proposal by the relayers. Depending on what semantics you want, you might want to mint tokens instead of transferring them. 
    - Note: In the present implementation you will have to match the method parameters exactly (to, amount, resource ID), or fork the Go code and change how the call is constructed. We plan to make this more flexible the next release. 
2. Deploy the chainbridge pallet and the additional pallet.
3. Follow the instructions for Eth -> Substrate transfers. Use any resource ID you want and register it with the utf-8 encoding of the call name (You can use a tool like this to compute it: https://onlineutf8tools.com/convert-utf8-to-hexadecimal)

Let us know if you have any other questions.

**Comment by ksr30** [comment]
Thanks, @ansermino for the detailed explanation. I am closing this issue for now.

**Comment by ansermino** [comment]
@ksr30 I suspect you require the option `"useExtendedCall": "true"` in the ChainBridge config https://chainbridge.chainsafe.io/configuration/#substrate-options

This has unfortunately been causing issues for a number of people. We had to include it to maintain backwards compatibility but will be deprecating it on the next major release.

**Comment by ksr30** [comment]
No success @ansermino .. same error

**Comment by ansermino** [comment]
@ksr30 What version of substrate are you using? What version of GSRPC? Would be good if you can share code or any other details.

**Comment by ksr30** [comment]
Hey, @P1sar @ansermino sorry I missed the notification ... problem still exists

**Comment by P1sar** [comment]
> @ksr30 What version of substrate are you using? What version of GSRPC? Would be good if you can share code or any other details.

@ksr30  Can you please answer quoted question?

**Comment by P1sar** [comment]
Close due to inactivity
